helper_vm_ip: 192.168.86.180
bootstrap_ignition_url: "http://{{helper_vm_ip}}:8080/ignition/bootstrap.ign"
config:
  provider: vsphere
  base_domain: example.com
  cluster_name: ocp4
  fips: false
  installer_ssh_key: "{{ lookup('file', '~/.ssh/ocp4.pub') }}"
  pull_secret: {"auths": ...}
vcenter:
  ip: 192.168.86.100
  datastore: datastore1
  network: VM Network
  service_account_username: administrator@vsphere.local
  service_account_password: something
  admin_username: administrator@vsphere.local
  admin_password: something
  datacenter: dc
  folder_absolute_path:
  vm_power_state: poweredon
  template_name: rhcos-vmware
worker_vms:
  - { name: "worker0", macaddr: "00:50:56:a8:aa:a5", ipaddr: "192.168.86.185"}
  - { name: "worker1", macaddr: "00:50:56:a8:aa:a6", ipaddr: "192.168.86.186"}
  - { name: "worker2", macaddr: "00:50:56:a8:aa:a7", ipaddr: "192.168.86.187"}
static_ip:
  gateway: 192.168.86.1
  netmask: 255.255.255.0
  dns: "{{ helper_vm_ip }}"
  network_interface_name: ens192
ntp:
  custom: false
  ntp_server_list:
    - 0.rhel.pool.ntp.org
    - 1.rhel.pool.ntp.org
