---
- hosts: localhost
  gather_facts: True
  environment:
    PATH: "{{ playbook_dir }}/bin:{{ ansible_env.PATH }}"
  tasks:
    - name: Run all the common tasks
      import_role:
        name: common
- hosts: localhost
  gather_facts: False
  environment:
    PATH: "{{ playbook_dir }}/bin:{{ ansible_env.PATH }}"
    GOVC_USERNAME: "{{ vcenter.admin_username }}"
    GOVC_PASSWORD: "{{ vcenter.admin_password }}"
    GOVC_URL: "https://{{ vcenter.ip }}"
    GOVC_DATACENTER: "{{ datacenter }}"
    GOVC_INSECURE: 1
  tasks:
    - name: Run the vmware role to setup vCenter folder
      import_role:
        name: vmware
    - name: Reset the vcenter.vm_power_state to poweredoff
      set_fact:
        vcenter: "{{ vcenter | combine({'vm_power_state': 'poweredoff'}, recursive=True) }}"
    - name: Echo the value of the variable vcenter.vm_power_state
      debug: var=vcenter.vm_power_state
    - name: Run steps specific to DHCP and PXE boot
      import_role:
        name: dhcp_pxe
    - name: Run steps for static ip setup of VMs
      import_role:
        name: static_ips
